{% set name = "flwr" %}
{% set version = "1.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/flwr-{{ version }}.tar.gz
  sha256: 99e869d29bcebe2fa585920cff4f059fb22585be59e3ffc2f017da4df82879a9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - flwr = flwr.cli.app:app
    - flower-driver-api = flwr.server:run_driver_api
    - flower-fleet-api = flwr.server:run_fleet_api
    - flower-superlink-api = flwr.server:run_superlink
    - flower-client-app = flwr.client:run_client_app
    - flower-server-app = flwr.server:run_server_app
    - flower-simulation = flwr.simulation:run_simulation_from_cli

requirements:
  host:
    - pip
    - poetry-core >=1.4.0
    - python >=3.8,<4.0
  run:
    # There is some snafu with grpcio version availability on Conda, removing some pinning and hoping for the best...
    # Upstream also using some unconventional Protobuf version numbers...
    - python >=3.8,<4.0
    - numpy >=1.21.0,<2.0.0
    - grpcio >=1.60.0,<2.0.0
    - protobuf # >=4.25.2,<5.0.0
    - cryptography >=42.0.4,<43.0.0
    - pycryptodome >=3.18.0,<4.0.0
    - iterators >=0.0.2,<0.0.3
    - typer >=0.9.0,<0.10.0
    - tomli >=2.0.1,<3.0.0

test:
  imports:
    - flwr
  commands:
    # Remove pip check see above
    # - pip check
    - flwr --help
    - flower-driver-api --help
    - flower-fleet-api --help
    - flower-superlink --help
    - flower-client-app --help
    - flower-server-app --help
    - flower-simulation --help
  requires:
    - pip

about:
  home: https://flower.ai
  doc_url: https://flower.ai/docs/
  dev_url: https://github.com/adap/flower
  summary: Flower - A Friendly Federated Learning Framework
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tanertopal
    - danieljanes
    - flwrmachine
    - thewchan
