{% set name = "flwr" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/flwr-{{ version }}.tar.gz
  sha256: eb419faf80899efe12c3b9fb54d0b4a0eb03184eee2cf6e45c72b347326caef4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.7,<4.0
  run:
    - python >=3.7,<4.0
    - grpcio >=1.43.0,<2.0.0
    - iterators >=0.0.2,<0.0.3
    - numpy >=1.21.0,<2.0.0
    - protobuf >=3.19.0,<4.0.0
    - importlib-metadata >=4.0.0,<5.0.0

test:
  imports:
    - flwr
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://flower.dev
  doc_url: https://flower.dev/docs/
  dev_url: https://github.com/adap/flower
  summary: Flower - A Friendly Federated Learning Framework
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
